// vue/src/components/ServiceBtn.vue
<template>
  <div class="service">
    <div class="s_b_switch" @click="swithUserInfo">{{userInfoEnable? '启用[用户信息]': '关闭[用户信息]'}}</div>
    <div class="s_b_switch" @click="swithProduct">{{productEnable? '启用[咨询对象]': '关闭[咨询对象]'}}</div>
    <div class="s_b_switch" @click="swithTicket">{{ticketEnable? '启用[工单信息]': '关闭[工单信息]'}}</div>
    <div class="s_b_switch" @click="openWebsiteToSearch">{{'自定义搜索关键词 - 第三方网站链接示例（如：公司官网）'}}</div>
    <div class="s_b_switch" @click="openPlugInToSearch">{{'自定义搜索关键词 - 网页插件链接示例'}}</div>
    <div class="s_b_switch service_btn" @click="toService">
      联系客服
    </div>

    <div class="des" v-show="userInfoEnable">
      <div>用户信息</div>
      <div>{{userInfo}}</div>
    </div>

    <div class="des" v-show="productEnable">
      <div>咨询对象</div>
      <div>{{product}}</div>
    </div>

    <div class="des" v-show="ticketEnable">
      <div>工单信息</div>
      <div>{{ticket}}</div>
    </div>
  </div>
</template>

<script>
import RXUdeskJS from '../package/udesk-js-link'
import UdeskUrlMixin from '../mixins/udesk-url'
export default {
  mixins: [UdeskUrlMixin],
  props: {
    userInfo: {
      type: Object,
      default() {
        return null
      }
    },
    product: {
      type: Object,
      default() {
        return null
      }
    },
    ticket: {
      type: Object,
      default() {
        return null
      }
    }
  },
  data() {
    return {
      userInfoEnable: false,
      productEnable: false,
      ticketEnable: false,
    }
  },
  methods: {
    swithUserInfo() {
      let enable = !this.userInfoEnable;
      if (!enable) return; // 登录后不会清空了
      this.userInfoEnable = enable;
    },
    swithProduct() {
      let enable = !this.productEnable;
      this.productEnable = enable;
    },
    swithTicket() {
      let enable = !this.ticketEnable;
      this.ticketEnable = enable;
    },
    openWebsiteToSearch() {
      RXUdeskJS.websiteToSearch('srxboys_website')
    },
    openPlugInToSearch() {
      RXUdeskJS.plugInToSearch('srxboys_plug')
    },
    toService() {
      let url = '';
      if (this.userInfoEnable || this.userInfo) {
        RXUdeskJS.setCustomer(this.userInfo)
      }

      if (this.productEnable || this.product) {
        url = RXUdeskJS.getProductUrlAutoPrefix(this.product)
      }
      else {
        url = RXUdeskJS.getNoneProductUrl()
      }

      if (this.ticketEnable || this.ticket) {
        let ticketUrl = RXUdeskJS.getTicketUrl(this.ticket)
        if (url) {
          url += '&' + ticketUrl;
        }
        else {
          url = ticketUrl;
        }
      }
      console.log('url=>', url)
      this.ud_toSeriveMinin();
      RXUdeskJS.toServiceIM(url);
    }
  }
}
</script>

<style scoped>

.service {
  padding: 0 15px;
}
.s_b_switch {
  margin-top: 20px;
  width: 100%;
  height: 40px;
  background-color: aqua;
  color: #708090;
  display: flex;
  justify-content: center;
  align-items: center;
  border-radius: 4px;
}

.service_btn {
  color: blue;
  background-color: burlywood;
}

.des {
  margin-top: 30px;
  color: darkgray;
  line-height: 18px;
  font-size: 12px;
}
</style>

// react/src/components/ServiceBtn.js
import React from 'react';
import PropType from 'prop-types'

import RXUdeskJS from '../package/udesk-js-link'

export default class TabBar extends React.Component {

  static propType = {
    userInfo: PropType.object,
    product: PropType.object,
    ticket: PropType.object,
  }

  constructor(props) {
    super(props);
    this.state = {
      userInfoEnable: false,
      productEnable: false,
      ticketEnable: false,
    }
  }

  swithUserInfo = () => {
    let enable = !this.state.userInfoEnable;
    if (!enable) return; // 登录后不会清空了
    this.setState({  userInfoEnable: enable })
  }

  swithProduct = () => {
    let enable = !this.state.productEnable;
    this.setState({ productEnable: enable })
  }

  swithTicket = () => {
    let enable = !this.state.ticketEnable;
    this.setState({ ticketEnable: enable })
  }

  openWebsiteToSearch = () => {
    RXUdeskJS.websiteToSearch('srxboys_website')
  }

  openPlugInToSearch = () => {
    RXUdeskJS.plugInToSearch('srxboys_plug')
  }

  toService = () => {
    let url = '';
      if (this.state.userInfoEnable || this.props.userInfo) {
        RXUdeskJS.setCustomer(this.props.userInfo)
      }

      if (this.state.productEnable || this.props.product) {
        url = RXUdeskJS.getProductUrlAutoPrefix(this.props.product)
      }
      else {
        url = RXUdeskJS.getNoneProductUrl()
      }

      if (this.state.ticketEnable || this.props.ticket) {
        let ticketUrl = RXUdeskJS.getTicketUrl(this.props.ticket)
        if (url) {
          url += '&' + ticketUrl;
        }
        else {
          url = ticketUrl;
        }
      }
      console.log('url=>', url)
      RXUdeskJS.toServiceIM(url);
  }

  render() {
    return (
      <div className="service">
        <button className="s_b_switch" onClick={this.swithUserInfo}>{this.state.userInfoEnable ? '启用[用户信息]' : '关闭[用户信息]'}</button>
        <button className="s_b_switch" onClick={this.swithProduct}>{this.state.productEnable ? '启用[咨询对象]': '关闭[咨询对象]'}</button>
        <button className="s_b_switch" onClick={this.swithTicket}>{this.state.ticketEnable ? '启用[工单信息]': '关闭[工单信息]'}</button>
        <button className="s_b_switch" onClick={this.openWebsiteToSearch}>{'自定义搜索关键词 - 第三方网站链接示例（如：公司官网）'}</button>
        <button className="s_b_switch" onClick={this.openPlugInToSearch}>{'自定义搜索关键词 - 网页插件链接示例'}</button>
        <button className={["s_b_switch", 'service_btn'].join(' ')} onClick={this.toService}>联系客服</button>

        {
          this.state.userInfoEnable?
          <div class="des">
            <div>用户信息</div>
            <div>{
            this.props.userInfo && typeof this.props.userInfo === 'object' ?
              JSON.stringify(this.props.userInfo)
            : null
            }</div>
          </div>
          : null
        }

        {
          this.state.productEnable?
          <div class="des">
            <div>咨询对象</div>
            <div>{
            this.props.product && typeof this.props.product === 'object' ?
              JSON.stringify(this.props.product)
            : null
            }</div>
          </div>
          : null
        }

        {
          this.state.ticketEnable?
          <div class="des">
            <div>工单信息</div>
            <div>{
              this.props.ticket && typeof this.props.ticket === 'object' ?
                JSON.stringify(this.props.ticket)
              : null
            }</div>
          </div>
          : null
        }
      </div>
    )
  }
}
